const byId = (path) => (id) => `${path}/${encodeURIComponent(id)}`;

export const API_ENDPOINTS = {
  admin: {
    login: "/admin/login",
    register: "/admin/register",
    profile: "/admin/getAdmin",
    verify: "/admin/verifyAdmin",
    updateDetails: byId("/admin/updateAdminDetails"),
    update: byId("/admin/updateAdmin"),
    updateImage: byId("/admin/updateAdminImage"),
    changePassword: byId("/admin/ChangePassword"),
  },
  users: {
    login: "/user/login",
    register: "/user/register",
    sendOtp: "/user/sendOTP",
    validateOtp: "/user/validateOtp",
    resetPassword: "/user/resetPasswordByUsernameOrEmail",
    list: "/user/getAllUser",
    get: byId("/user/getUserById"),
    update: byId("/user/updateUserById"),
    remove: byId("/user/deleteUserById"),
    byEmail: byId("/user/getUserByEmail"),
    byUsername: byId("/user/getUserByUserName"),
  },
  blogs: {
    list: "/blog/getAllBlogs",
    create: "/blog/createBlog",
    update: byId("/blog/updateBlogByID"),
    updateStatus: byId("/blog/updateBlogStatusByID"),
    remove: byId("/blog/deleteBlogByID"),
  },
  blogReactions: {
    updateStatus: "/blogReaction/updateStatus",
    byUser: byId("/blogReaction/getByUser_id"),
    counts: "/blogReaction/getAllBlogLikeCounts",
  },
  blogReads: {
    updateStatus: "/blogRead/updateStatus",
    byUser: byId("/blogRead/getByUser_id"),
    counts: "/blogRead/getAllBlogReadCounts",
  },
  package: {
    create: "/payapi/createPackage",
    list: "/payapi/getAllPackage",
    get: byId("/payapi/getPackageById"),
    update: byId("/payapi/updatePackageByID"),
    remove: byId("/payapi/deletePackageByID"),
  },
  cart: {
    create: "/payapi/createCart",
    list: "/payapi/getAllCart",
    get: byId("/payapi/getCartById"),
    update: byId("/payapi/updateCartByID"),
    remove: byId("/payapi/deleteCartByID"),
  },
  payments: {
    list: "/payapi/getAllPayments",
    createStripe: "/payapi/payStripe",
    store: "/payapi/store-payment-details",
    stripeDetails: byId("/payapi/getpayStripeID"),
    get: byId("/payapi/payment-details"),
    byUser: byId("/payapi/payment-detailsbyuserid"),
    byUserAndPackage: (userId, packageId) =>
      `/payapi/payment-detailsbyuseridpackageid/${encodeURIComponent(userId)}/${encodeURIComponent(packageId)}`,
    sendMail: "/payapi/sendmail",
  },
  feedback: {
    list: "/feedback/getAllFeedbacks",
    remove: byId("/feedback/deleteFeedbackByID"),
    create: "/feedback/createFeedback",
    get: byId("/feedback/getFeedbackById"),
    byBlog: byId("/feedback/getAllFeedbacksByBlogID"),
  },
  coupons: {
    list: "/payapi/getAllCoupon",
    create: "/payapi/createCoupon",
    update: byId("/payapi/updateCouponByID"),
    remove: byId("/payapi/deleteCouponByID"),
    get: byId("/payapi/getCouponById"),
    apply: byId("/payapi/applycoupon"),
  },
  billing: {
    create: "/payapi/createBilling",
    list: "/payapi/getAllBilling",
    get: byId("/payapi/getBillingById"),
    update: byId("/payapi/updateBillingByID"),
    byUser: byId("/payapi/billing-detailsbyuserid"),
    updateByUser: byId("/payapi/updateBillingByUserID"),
  },
  contacts: {
    create: "/contact/contactAdd",
    list: "/contact/getAllContact",
    get: byId("/contact/getContactById"),
    remove: byId("/contact/deleteContactById"),
  },
  videos: {
    upload: "/videosUpload/upload",
    listAll: "/videosUpload/getAll",
    get: byId("/videosUpload/getById"),
    update: byId("/videosUpload/update"),
    removeVideo: byId("/videosUpload/deleteById"),
    byPackage: "/videosUpload/getAllByPackageType",
    byUser: "/videosUpload/getByUserId",
    recordView: (id) => `/videosUpload/${encodeURIComponent(id)}/view`,
    byUserAndPackage: "/videosUpload/getVideosByUser_idWithPackageType",
    adminUpload: "/videosUpload/admin/upload",
    list: "/videosUpload/admin/getAll",
    adminGet: byId("/videosUpload/admin/getById"),
    adminUpdate: byId("/videosUpload/admin/update"),
    remove: byId("/videosUpload/admin/deleteById"),
    byAdmin: "/videosUpload/admin/getByAdminId",
  },
  videoCounts: {
    byUser: "/videosCount/getAllUsedVideoCountByUserId",
  },
};
